from __future__ import annotations

import shlex
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Optional


REPO_ROOT = Path(__file__).resolve().parents[3]
ENV_PATH = REPO_ROOT / ".env"
MAX_DNS_LABEL_BYTES = 63
MAX_DNS_NAME_BYTES = 255
MAX_DNS_TXT_BYTES = 255
MAX_NETBIOS_NAME_BYTES = 15
MODEL_TXT_PREFIX = "model="
ADISK_DEFAULT_DISK_KEY = "dk2"
ADISK_DISK_UUID_EXAMPLE = "12345678-1234-1234-1234-123456789012"
ADISK_DISK_TXT_MID = "=adVF=0x1093,adVN="
ADISK_DISK_TXT_SUFFIX = ",adVU="

DEFAULTS = {
    "TC_HOST": "root@192.168.1.101",
    "TC_SSH_OPTS": "-o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa -o KexAlgorithms=+diffie-hellman-group14-sha1 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null",
    "TC_NET_IFACE": "bridge0",
    "TC_SHARE_NAME": "Data",
    "TC_SAMBA_USER": "admin",
    "TC_NETBIOS_NAME": "TimeCapsule",
    "TC_PAYLOAD_DIR_NAME": ".samba4",
    "TC_MDNS_INSTANCE_NAME": "Time Capsule Samba 4",
    "TC_MDNS_HOST_LABEL": "timecapsulesamba4",
    "TC_MDNS_DEVICE_MODEL": "TimeCapsule",
}

REQUIRED_ENV_KEYS = [
    "TC_HOST",
    "TC_PASSWORD",
    "TC_NET_IFACE",
    "TC_SHARE_NAME",
    "TC_SAMBA_USER",
    "TC_NETBIOS_NAME",
    "TC_PAYLOAD_DIR_NAME",
    "TC_MDNS_INSTANCE_NAME",
    "TC_MDNS_HOST_LABEL",
    "TC_MDNS_DEVICE_MODEL",
]

CONFIG_FIELDS = [
    ("TC_HOST", "Time Capsule SSH target", DEFAULTS["TC_HOST"], False),
    ("TC_PASSWORD", "Time Capsule root password", "", True),
    ("TC_NET_IFACE", "Network interface on the Time Capsule", DEFAULTS["TC_NET_IFACE"], False),
    ("TC_SHARE_NAME", "SMB share name", DEFAULTS["TC_SHARE_NAME"], False),
    ("TC_SAMBA_USER", "Samba username", DEFAULTS["TC_SAMBA_USER"], False),
    ("TC_NETBIOS_NAME", "Samba NetBIOS name", DEFAULTS["TC_NETBIOS_NAME"], False),
    ("TC_PAYLOAD_DIR_NAME", "Persistent payload directory name", DEFAULTS["TC_PAYLOAD_DIR_NAME"], False),
    ("TC_MDNS_INSTANCE_NAME", "mDNS SMB instance name", DEFAULTS["TC_MDNS_INSTANCE_NAME"], False),
    ("TC_MDNS_HOST_LABEL", "mDNS host label", DEFAULTS["TC_MDNS_HOST_LABEL"], False),
    ("TC_MDNS_DEVICE_MODEL", "mDNS device model hint", DEFAULTS["TC_MDNS_DEVICE_MODEL"], False),
]

ENV_FILE_KEYS = [
    "TC_HOST",
    "TC_PASSWORD",
    "TC_SSH_OPTS",
    "TC_NET_IFACE",
    "TC_SHARE_NAME",
    "TC_SAMBA_USER",
    "TC_NETBIOS_NAME",
    "TC_PAYLOAD_DIR_NAME",
    "TC_MDNS_INSTANCE_NAME",
    "TC_MDNS_HOST_LABEL",
    "TC_MDNS_DEVICE_MODEL",
]

CONFIG_HEADER = """# Local user/device configuration for TimeCapsuleSMB.
# Generated by tcapsule configure
"""


@dataclass(frozen=True)
class AppConfig:
    values: dict[str, str]

    def get(self, key: str, default: str = "") -> str:
        return self.values.get(key, default)

    def require(self, key: str) -> str:
        value = self.get(key)
        if not value:
            raise SystemExit(f"Missing required setting in .env: {key}")
        return value


def parse_env_value(raw_value: str) -> str:
    value = raw_value.strip()
    if not value:
        return ""
    try:
        tokens = shlex.split(value)
        # A single parsed token means the env value was one scalar, possibly
        # quoted. Multi-token values such as TC_SSH_OPTS must remain intact and
        # are interpreted later by the transport layer.
        if len(tokens) == 1:
            return tokens[0]
        return value
    except ValueError:
        return value.strip("'\"")


def parse_env_values(path: Path, *, defaults: Optional[dict[str, str]] = None) -> dict[str, str]:
    values = dict(DEFAULTS if defaults is None else defaults)
    if not path.exists():
        return values
    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = parse_env_value(value)
    return values


def load_config(path: Path = ENV_PATH) -> AppConfig:
    return AppConfig(parse_env_values(path))


def missing_required_keys(values: dict[str, str]) -> list[str]:
    return [key for key in REQUIRED_ENV_KEYS if not values.get(key, "")]


def shell_quote(value: str) -> str:
    return shlex.quote(value)


def extract_host(target: str) -> str:
    return target.split("@", 1)[1] if "@" in target else target


def _contains_invalid_control_character(value: str) -> bool:
    return any(ord(ch) < 0x20 or ord(ch) == 0x7F for ch in value)


def build_instance_fqdn(instance_name: str, service_type: str) -> Optional[str]:
    value = f"{instance_name}.{service_type}"
    if len(value.encode("utf-8")) > MAX_DNS_NAME_BYTES:
        return None
    return value


def build_mdns_device_model_txt(value: str) -> Optional[str]:
    txt = MODEL_TXT_PREFIX + value
    if len(txt.encode("utf-8")) > MAX_DNS_TXT_BYTES:
        return None
    return txt


def build_adisk_share_txt(value: str) -> Optional[str]:
    txt = f"{ADISK_DEFAULT_DISK_KEY}{ADISK_DISK_TXT_MID}{value}{ADISK_DISK_TXT_SUFFIX}{ADISK_DISK_UUID_EXAMPLE}"
    if len(txt.encode("utf-8")) > MAX_DNS_TXT_BYTES:
        return None
    return txt


def validate_dns_label(value: str, field_name: str) -> Optional[str]:
    if not value:
        return f"{field_name} cannot be blank."
    if len(value.encode("utf-8")) > MAX_DNS_LABEL_BYTES:
        return f"{field_name} must be {MAX_DNS_LABEL_BYTES} bytes or fewer."
    if "." in value:
        return f"{field_name} must not contain dots."
    if _contains_invalid_control_character(value):
        return f"{field_name} contains an invalid control character."
    return None


def validate_dns_name(value: str, field_name: str) -> Optional[str]:
    if not value:
        return f"{field_name} cannot be blank."
    if len(value.encode("utf-8")) > MAX_DNS_NAME_BYTES:
        return f"{field_name} must be {MAX_DNS_NAME_BYTES} bytes or fewer."
    if value.startswith("."):
        return f"{field_name} contains an empty label."
    stripped = value[:-1] if value.endswith(".") else value
    if not stripped:
        return f"{field_name} contains an empty label."
    if _contains_invalid_control_character(value):
        return f"{field_name} contains an invalid control character."
    for label in stripped.split("."):
        if not label:
            return f"{field_name} contains an empty label."
        if len(label.encode("utf-8")) > MAX_DNS_LABEL_BYTES:
            return f"{field_name} contains a label longer than {MAX_DNS_LABEL_BYTES} bytes."
    return None


def validate_single_dns_label(value: str, field_name: str) -> Optional[str]:
    return validate_dns_label(value, field_name)


def validate_mdns_device_model(value: str, field_name: str) -> Optional[str]:
    if not value:
        return f"{field_name} cannot be blank."
    if build_mdns_device_model_txt(value) is None:
        return f"{field_name} must be 249 bytes or fewer."
    if _contains_invalid_control_character(value):
        return f"{field_name} contains an invalid control character."
    return None


def validate_adisk_share_name(value: str, field_name: str) -> Optional[str]:
    if not value:
        return f"{field_name} cannot be blank."
    if build_adisk_share_txt(value) is None:
        max_share_bytes = (
            MAX_DNS_TXT_BYTES
            - len(ADISK_DEFAULT_DISK_KEY.encode("utf-8"))
            - len(ADISK_DISK_TXT_MID.encode("utf-8"))
            - len(ADISK_DISK_TXT_SUFFIX.encode("utf-8"))
            - len(ADISK_DISK_UUID_EXAMPLE.encode("utf-8"))
        )
        return f"{field_name} must be {max_share_bytes} bytes or fewer."
    if _contains_invalid_control_character(value):
        return f"{field_name} contains an invalid control character."
    return None


def validate_netbios_name(value: str, field_name: str) -> Optional[str]:
    if not value:
        return f"{field_name} cannot be blank."
    if len(value.encode("utf-8")) > MAX_NETBIOS_NAME_BYTES:
        return f"{field_name} must be {MAX_NETBIOS_NAME_BYTES} bytes or fewer."
    if _contains_invalid_control_character(value):
        return f"{field_name} contains an invalid control character."
    return None


CONFIG_VALIDATORS: dict[str, Callable[[str, str], Optional[str]]] = {
    "TC_SHARE_NAME": validate_adisk_share_name,
    "TC_NETBIOS_NAME": validate_netbios_name,
    "TC_MDNS_INSTANCE_NAME": validate_dns_label,
    "TC_MDNS_HOST_LABEL": validate_dns_label,
    "TC_MDNS_DEVICE_MODEL": validate_mdns_device_model,
}


def render_env_text(values: dict[str, str]) -> str:
    lines = [CONFIG_HEADER.rstrip(), ""]
    for key in ENV_FILE_KEYS:
        lines.append(f"{key}={shell_quote(values[key])}")
    lines.append("")
    return "\n".join(lines)


def write_env_file(path: Path, values: dict[str, str]) -> None:
    path.write_text(render_env_text(values))
