from __future__ import annotations

import shlex
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
ENV_PATH = REPO_ROOT / ".env"

DEFAULTS = {
    "TC_HOST": "root@192.168.1.101",
    "TC_SSH_OPTS": "-o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa -o KexAlgorithms=+diffie-hellman-group14-sha1 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null",
    "TC_NET_IFACE": "bridge0",
    "TC_SHARE_NAME": "Data",
    "TC_SAMBA_USER": "admin",
    "TC_NETBIOS_NAME": "TimeCapsule",
    "TC_PAYLOAD_DIR_NAME": "samba4",
    "TC_MDNS_INSTANCE_NAME": "Time Capsule Samba 4",
    "TC_MDNS_HOST_LABEL": "timecapsulesamba4",
}

REQUIRED_ENV_KEYS = [
    "TC_HOST",
    "TC_PASSWORD",
    "TC_NET_IFACE",
    "TC_SHARE_NAME",
    "TC_SAMBA_USER",
    "TC_NETBIOS_NAME",
    "TC_PAYLOAD_DIR_NAME",
    "TC_MDNS_INSTANCE_NAME",
    "TC_MDNS_HOST_LABEL",
]

CONFIG_FIELDS = [
    ("TC_HOST", "Time Capsule SSH target", DEFAULTS["TC_HOST"], False),
    ("TC_PASSWORD", "Time Capsule root password", "", True),
    ("TC_NET_IFACE", "Network interface on the Time Capsule", DEFAULTS["TC_NET_IFACE"], False),
    ("TC_SHARE_NAME", "SMB share name", DEFAULTS["TC_SHARE_NAME"], False),
    ("TC_SAMBA_USER", "Samba username", DEFAULTS["TC_SAMBA_USER"], False),
    ("TC_NETBIOS_NAME", "Samba NetBIOS name", DEFAULTS["TC_NETBIOS_NAME"], False),
    ("TC_PAYLOAD_DIR_NAME", "Persistent payload directory name", DEFAULTS["TC_PAYLOAD_DIR_NAME"], False),
    ("TC_MDNS_INSTANCE_NAME", "mDNS SMB instance name", DEFAULTS["TC_MDNS_INSTANCE_NAME"], False),
    ("TC_MDNS_HOST_LABEL", "mDNS host label", DEFAULTS["TC_MDNS_HOST_LABEL"], False),
]

CONFIG_HEADER = """# Local user/device configuration for TimeCapsuleSMB.
# Generated by tcapsule configure
"""


@dataclass(frozen=True)
class AppConfig:
    values: dict[str, str]

    def get(self, key: str, default: str = "") -> str:
        return self.values.get(key, default)

    def require(self, key: str) -> str:
        value = self.get(key)
        if not value:
            raise SystemExit(f"Missing required setting in .env: {key}")
        return value


def parse_env_value(raw_value: str) -> str:
    value = raw_value.strip()
    try:
        return shlex.split(value)[0] if value else ""
    except ValueError:
        return value.strip("'\"")


def parse_env_values(path: Path, *, defaults: dict[str, str] | None = None) -> dict[str, str]:
    values = dict(DEFAULTS if defaults is None else defaults)
    if not path.exists():
        return values
    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = parse_env_value(value)
    return values


def load_config(path: Path = ENV_PATH) -> AppConfig:
    return AppConfig(parse_env_values(path))


def missing_required_keys(values: dict[str, str]) -> list[str]:
    return [key for key in REQUIRED_ENV_KEYS if not values.get(key, "")]


def shell_quote(value: str) -> str:
    return shlex.quote(value)


def extract_host(target: str) -> str:
    return target.split("@", 1)[1] if "@" in target else target


def render_env_text(values: dict[str, str]) -> str:
    lines = [CONFIG_HEADER.rstrip(), ""]
    for key, _, _, _ in CONFIG_FIELDS:
        lines.append(f"{key}={shell_quote(values[key])}")
    lines.append("")
    return "\n".join(lines)


def write_env_file(path: Path, values: dict[str, str]) -> None:
    path.write_text(render_env_text(values))
