#!/usr/bin/env python3
from __future__ import annotations

import getpass
import shlex
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = REPO_ROOT / ".env"


FIELDS = [
    ("TC_HOST", "Time Capsule SSH target", "root@192.168.1.101", False),
    ("TC_PASSWORD", "Time Capsule root password", "", True),
    ("TC_NET_IFACE", "Network interface on the Time Capsule", "bridge0", False),
    ("TC_SHARE_NAME", "SMB share name", "Data", False),
    ("TC_SAMBA_USER", "Samba username", "admin", False),
    ("TC_NETBIOS_NAME", "Samba NetBIOS name", "TimeCapsule", False),
    ("TC_PAYLOAD_DIR_NAME", "Persistent payload directory name", "samba4", False),
    ("TC_MDNS_INSTANCE_NAME", "mDNS SMB instance name", "Time Capsule Samba 4", False),
    ("TC_MDNS_HOST_LABEL", "mDNS host label", "timecapsulesamba4", False),
]


HEADER = """# Local user/device configuration for TimeCapsuleSMB.
# Generated by scripts/configure.py
"""


def parse_existing(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    if not path.exists():
        return data
    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        try:
            data[key] = shlex.split(value)[0] if value else ""
        except ValueError:
            data[key] = value.strip("'\"")
    return data


def prompt(label: str, default: str, secret: bool) -> str:
    suffix = f" [{default}]" if default and not secret else ""
    text = f"{label}{suffix}: "
    value = getpass.getpass(text) if secret else input(text)
    if value == "":
        return default
    return value


def shell_quote(value: str) -> str:
    return shlex.quote(value)


def main() -> None:
    existing = parse_existing(ENV_PATH)
    values: dict[str, str] = {}

    print(f"Writing {ENV_PATH}")
    print("\033[31mPress Enter\033[0m to accept the current/default value.\n")

    for key, label, default, secret in FIELDS:
        current = existing.get(key, default)
        values[key] = prompt(label, current, secret)

    lines = [HEADER.rstrip(), ""]
    for key, _, _, _ in FIELDS:
        lines.append(f"{key}={shell_quote(values[key])}")
    lines.append("")

    ENV_PATH.write_text("\n".join(lines))
    print(f"\nWrote {ENV_PATH}")
    print("Next steps:")
    print("  1. Review .env")
    print("  2. If you are doing build work, configure build/.env separately from build/.env.example")


if __name__ == "__main__":
    main()
